server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/referral-db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:  
      ddl-auto: update
    show-sql: true
    
  profiles:
    active: dev
    

  web:
    cors:
      mappings:
        path-pattern: "/api/**"
        allowed-origins: "http://localhost:5173"
        allowed-methods: "GET, POST, PUT, DELETE"
        allowed-headers: "*"
        allow-credentials: true
      
logging:
   level:
     org.springframework.web: DEBUG
     com.example: INFO
  
    